# Generated by Django 4.2.26 on 2025-11-27 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months', models.PositiveIntegerField(unique=True)),
                ('label', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'months'],
            },
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='saccos/')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('google_sheet_id', models.CharField(blank=True, help_text='Google Sheet ID for storing financing requests', max_length=200)),
                ('google_sheet_name', models.CharField(blank=True, default='Sheet1', help_text='Name of the sheet tab within the Google Sheet', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sacco',
                'verbose_name_plural': 'Saccos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('national_id', models.CharField(max_length=20)),
                ('town_of_residence', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=300)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variation_details', models.CharField(blank=True, max_length=200)),
                ('sacco_name', models.CharField(max_length=200)),
                ('payment_months', models.PositiveIntegerField()),
                ('monthly_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated monthly payment (can be set by admin)', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('submitted', 'Submitted to Sacco'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('synced_to_sheet', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('customer_email_sent', models.BooleanField(default=False)),
                ('admin_email_sent', models.BooleanField(default=False)),
                ('customer_notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_timeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='financing.paymenttimeline')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_requests', to='store.product')),
                ('sacco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_requests', to='financing.sacco')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financing_requests', to=settings.AUTH_USER_MODEL)),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productvariation')),
            ],
            options={
                'verbose_name': 'Financing Request',
                'verbose_name_plural': 'Financing Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
